# Generated by Django 4.1.7 on 2023-02-28 19:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('car_location', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('seating_capacity', models.PositiveIntegerField(default=4)),
                ('rent_per_day', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(99)])),
                ('availability', models.BooleanField(null=True)),
                ('about', models.TextField(blank=True, max_length=355, null=True)),
                ('arac_foto_1', models.ImageField(blank=True, null=True, upload_to='car_fotolari/%Y/%m/')),
                ('arac_foto_2', models.ImageField(blank=True, null=True, upload_to='car_fotolari/%Y/%m/')),
                ('arac_foto_3', models.ImageField(blank=True, null=True, upload_to='car_fotolari/%Y/%m/')),
                ('car_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moto_location', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('seating_capacity', models.PositiveIntegerField(default=2)),
                ('rent_per_day', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)])),
                ('availability', models.BooleanField(null=True)),
                ('about', models.TextField(blank=True, max_length=355, null=True)),
                ('moto_foto_1', models.ImageField(blank=True, null=True, upload_to='motor_fotolari/%Y/%m/')),
                ('moto_foto_2', models.ImageField(blank=True, null=True, upload_to='motor_fotolari/%Y/%m/')),
                ('moto_foto_3', models.ImageField(blank=True, null=True, upload_to='motor_fotolari/%Y/%m/')),
                ('moto_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MotoReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('rez_date', models.DateField(auto_now_add=True)),
                ('total_price', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moto')),
            ],
        ),
        migrations.CreateModel(
            name='MotoFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.ManyToManyField(related_name='favori_set_moto', to='api.moto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('rez_date', models.DateField(auto_now_add=True)),
                ('total_price', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('araclar', models.ManyToManyField(related_name='favori_set', to='api.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
