# Generated by Django 4.1.7 on 2023-03-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_vehicle_favorites_alter_vehicle_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='favorite_user',
        ),
    ]
