# Generated by Django 4.1.7 on 2023-03-09 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_vehicle_arac_foto_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('M', 'Motocycle'), ('C', 'Car'), ('B', 'Bike')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='rent_per_day',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seating_capacity',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
